[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "configatron"
version = "0.0.0"
description = "General-purpose configuration based on annotations"
authors = ["Nick Badger <nicholas.badger@taev.dev>"]

[tool.poetry.dependencies]
python = ">=3.10"
tomli = { version = ">=2.0.1", python = "< 3.11" }

# Optional deps for specific backends
boto3 = { version = ">=1.26.63", optional = true }
keyring = { version = ">=23.13.1", optional = true }

[tool.poetry.group.dev.dependencies]
ipython = ">=7.29.0"
ruff = ">=0.0.239"
refurb = ">=1.10.0"
pytest = ">=7.2.1"
moto = {extras = ["secretsmanager"], version = "^4.1.1"}

[tool.poetry.extras]
aws-sm = ["boto3"]
os-keyvault = ["keyring"]

[tool.pytest.ini_options]
minversion = "7.0"
testpaths = [
    "tests/unittests",
]
addopts = "--import-mode=importlib"

[tool.ruff]
dummy-variable-rgx = "^__$"
line-length = 79
select = [
    "F",
    "E",
    "W",
    "C90",
    "B",
    "I",
    "N",
    "YTT",
    "S",
    "A",
    "C4",
    "ICN",
    "Q003",
    "PLC",
    "PLE",
    "PLR",
    "PLW",
    "RUF"
]
ignore = [
    "N818"
]

[tool.ruff.per-file-ignores]
"tests/*" = ["S"]

[tool.ruff.isort]
force-single-line = true

[tool.refurb]
ignore = []
